---
genPolicy: "None"
openAPISpec: "None"
generators:
- type: "no_params"
  assertions:
  - "@StatusCode == 200"
  tags:
  - " OWASP - OTG-CONFIG-006"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "sla"
  assertions:
  - "@StatusCode == 200 AND @ResponseTime < 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags:
  - "OWASP - OTG-AUTHN-002"
  severity: null
  database: null
  inactive: false
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: "Get:/api/v1/user-signup/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "auth_invalid"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags:
  - "OWASP A2"
  - "OWASP A5"
  - "OWASP A6"
  - "OWASP A7"
  - "[PIC DSS 3.0] 6.5.8"
  - "[PIC DSS 3.0] 6.5.10"
  - "OTG-AUTHN-004"
  severity: null
  database: null
  inactive: false
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "auth_invalid_empty"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags:
  - "OWASP A2"
  - "OWASP A5"
  - "OWASP A6"
  - "OWASP A7"
  - "[PIC DSS 3.0] 6.5.8"
  - "[PIC DSS 3.0] 6.5.10"
  - "OTG-AUTHN-004"
  severity: null
  database: null
  inactive: false
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "auth_invalid_sql"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags:
  - "OWASP A1"
  - "[PCI DSS 3.0] 6.5.1"
  - "OTG-AUTHN-004"
  severity: null
  database: null
  inactive: false
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "DDOS"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags:
  - "[PCI DSS 3.0] 6.5.2"
  severity: null
  database: null
  inactive: false
  matches:
  - name: "pageSize, page_size, maxResults, max_results"
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "XSS_Injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags:
  - "OWASP A3"
  - "[PIC DSS 3.0] 6.5.7"
  - "OWASP - OTG-INPVAL-001"
  - "OWASP - OTG-INPVAL-002"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "sql_injection_timebound"
  assertions:
  - "@ResponseTime < 7000 OR @ResponseTime > 10000"
  - "@StatusCode != 404"
  tags:
  - "OWASP A1"
  - "[PCI DSS 3.0] 6.5.1"
  - "OWASP - OTG-INPVAL-005"
  severity: null
  database:
    name: "MySQL"
    version: "5.7"
  inactive: false
  matches: []
- type: "log_Forging"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags:
  - "OWASP - Log Injection"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "invalid_datatype"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags:
  - "OWASP - OTG-BUSLOGIC-001"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "special_chars "
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags:
  - "OWASP - OTG-BUSLOGIC-001"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "null_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags:
  - "OWASP - OTG-BUSLOGIC-001"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "empty_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "negative_number"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags:
  - "OWASP - OTG-BUSLOGIC-001"
  severity: null
  database: null
  inactive: false
  matches: []
- type: "create"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags:
  - " OWASP - OTG-CONFIG-006"
  severity: null
  database: null
  inactive: false
  matches: []
